version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .docker/runtime.Dockerfile
    image: scraping-web:dev
    working_dir: /var/www/project/public
    volumes:
      - .:/var/www/project/public
      - .docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    ports:
      - 9021:80
